### ISSUE TITLE
[Hif] RFE: Build time switch for setting supported sources

### ISSUE THREAD

**Issue by Conan-Kudo** [hughsie/PackageKit#119]
<strike>For Mageia, I intend to use `/etc/distro.repos.d` (that will eventually be used in Fedora, planned for F25, see [this PR](https://github.com/rpm-software-management/dnf/pull/416) for details) for my repo configuration directory.

In addition, </strike>The hardcoded list of supported repositories is wrong for Mageia. We have our own list of supported repositories which differs quite a bit from Fedora's (for obvious reasons).

I *could* make a patch to change it when being built in Mageia, but I would prefer if a system to support different vendor configurations at build-time could be added to the Hif backend, so that Fedora and Mageia configurations can be maintained upstream.

**Comment by hughsie** [comment]
Right, if F25 is going to switch then we should probably make this configurable.

On a more general note: I'm not so keen spending hours of developer time on Mageia-specific patches. If Mageia wants to use something that's been developed for Fedora (and paid for by Red Hat) I don't think it's an unreasonable expectation for someone at Mageia to actually contribute the new functionality you guys need. I've seen quite a few requests across half-a-dozen projects for new functionality specifically for Mageia, and pretty much no actual patches. I think at some point you need to spend some time actually contributing code rather than just repeatedly pinging people about unsolved issues that only affect Mageia.

I don't want to sound aggressive, but if you want to build a new package management layer for a small distro sooner or later you have to write some code rather than asking everyone else to do the work.

**Comment by Conan-Kudo** [comment]
After spending quite a bit of time working out how to actually do this, I've submitted a pull request with rudimentary build-time vendor configuration for the Hif backend.

**Comment by Conan-Kudo** [comment]
I'm now using the same reposdir location as Fedora, so the only part that matters is setting supported sources.
