### ISSUE TITLE
[aptcc] maybe use Apt::Upgrade::Upgrade()

### ISSUE THREAD

**Issue by apachelogger** [hughsie/PackageKit#154]
I am not sure how long it's there, but apt-pkg actually has API to mark and resolve upgrades/updates, might be worth checking it out as a possible replacement for manually attempting to deal with upgrades:
`      bool Upgrade(pkgDepCache &Cache, int UpgradeMode, OpProgress * const Progress = NULL);`

**Comment by ximion** [comment]
Depending on the latest APT would be fine with me, there is no reason to stick with ancient API.
And, tbh, the aptcc backend will need some big refactoring...

**Comment by apachelogger** [comment]
So, I think we actually can't use the function. From what I see one can update single packages, which wouldn't work with the provided apt-pkg function as it is for wholesale upgrading of all available packages.

**Comment by dantti** [comment]
Yes, that's why updating packages goes through the same install path

Em 5 de set de 2016 12:57 PM, "Harald Sitter" <notifications@github.com>
escreveu:

So, I think we actually can't use the function. From what I see one can
update single packages, which wouldn't work with the provided apt-pkg
function as it is for wholesale upgrading of all available packages.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hughsie/PackageKit/issues/154#issuecomment-244777076>,
or mute the thread

**Comment by apachelogger** [comment]
Right. So kicking this issue to the bucket as we can't make use the API. We'll instead want to move forward on properly marking packages and letting the resolver retain auto flags, for which we can at a glance actually draw inspiration what `::Upgrade` does internally as we basically want to employ the same algorithm but with more control over what gets marked.
