### ISSUE TITLE
PackageKit synthesizes "Reason" and "Updates" field for .deb packages, but does not drop the original "Change Log" field that the information came from, resulting in needlessly duplicated information

### ISSUE THREAD

**Issue by Pointedstick** [hughsie/PackageKit#227]
PackageKit 1.1.7 in Kubuntu 17.10

For .deb packages that have a Change Log field, PackageKit appears to extract that information and synthesize two new fields with it: Reason and Updates. This is fine, but it doesn't discard the original Change Log field. This causes clients such as KDE Discover that pass on all fields from PackageKit to display needlessly duplicated information:

![more info](https://user-images.githubusercontent.com/1097249/33816599-441e5124-ddf7-11e7-9a47-242a2a2ea939.png)

If PackageKit continues to provide the original Change Log field aside from its synthesized Reason and Updates fields, then Discover developers would have to explicitly drop the Change Log field for .deb packages, which would mean adding the kind of special-case code that PackageKit is supposed to protect them from having to write :slightly_smiling_face:)

Downstream bug: https://bugs.kde.org/show_bug.cgi?id=387041

**Comment by ximion** [comment]
Well, just show either the Reason or Change Log, but not both? Or show just the reason and the changelog in case the user clicks on a Details button?
Or do not show the reason at all and always just show the changelog? (Take a look at what Apper does in this regard, I think the display it uses is very good)

I don't see the issue with PackageKit here, I pretty much only see an UX issue in Discover from the information given here.

**Comment by basak** [comment]
I suggest that this is a bug or shortcoming in the metadata abstraction in your API. You're trying to fit a round "changelog" Debian peg into a square "Reason and Change Log" hole. The API's representation of this metadata does not adequately support the representation of what has come from the Debian changelog format for UI presentation purposes, even though the original Debian changelog is fine.

By duplicating (a subset of) Change Log into Reason, you're hiding from your consumers the fact that you did the duplication. They cannot tell whether the Reason contains meaningful information or if you fabricated it.

If instead your API passed through a sentinel "there is no Reason" signal on Debian and Ubuntu, consumers would be more informed on how to deal with the situation. As it stands, you seem to be asking API consumers to heuristically second guess what you have done for the purposes of presentation. I think this points to the API being a leaky abstraction.

I'm not sure if this can be fixed properly without an API break though since otherwise it might unexpectedly change the behaviour of existing consumers. Perhaps as a workaround you could add a "reason is fabricated" boolean. As a hack, consumers could add a "assume provided reason is fabricated if using PackageKit versions ... and on Debian or a derivative".

**Comment by Pointedstick** [comment]
We aren't the ones duplicating Change Log into Reason and Updates. That data comes straight from PackageKit, and we just pass it on if it's present: https://cgit.kde.org/discover.git/tree/libdiscover/backends/PackageKitBackend/PackageKitResource.cpp#n241

We don't have a problem with PackageKit synthesizing new fields from the original ChangeLog field, but that creates a situation where if we pass on all information, we get duplicates, and if we add custom presentation-layer logic to hide one or the other, then it seems like we're working against the whole purpose of PackageKit, which is to abstract away these kids of implementation details. We want Discover to stay distro- and packaging-neutral, just like GNOME Software.

**Comment by ximion** [comment]
I disagree at least with part of these reasons. I do agree that the "Reason"/"Changelog" split is not ideal, it originated from Richards initial PK design and was added 10 years ago.

What you display as "Reason" in the UI is actually the `update_text` property, which is described as "The update text describing the update.", which I guess is a shorter, more human-readable version of the changelog.
That doesn't exist in Debian, so what we do is re-format an excerpt from the changlog so it can be Markdown-formatted a bit easier and set that as update text. For the actual `changelog` property, we emit the verbatim changelog text as the PK API requires.

So, this is all working as intended. I saw that the alpm backend seems to emit a raw untranslated "Update to a newer release" string for `update_text`, which IMO is the wrong behavior for this, since it doesn't provide what the API asks for. I guess that the misconception about the update_text property originates from that though.

So, `update_text` and `changelog` essentially provide the same information, only that `changelog` is geared more towards technically savy users who want to know all the details, and `update_text` is supposed to be a bit more terse.
Therefore, I think that the UX is wrong in displaying both things side-by-side, and I also think that "Reason" might not be the best text for this ("Summary" could be more accurate).
Personally, I would likely drop the display of `update_text` completely and just show the changelog excerpt to the user if they decide to view the details of that particular update.

Another thing is that in order to streamline this, we would need to break 10 years old API, so this won't happen for a thing like this (the absolute max we could do is deprecate one of the properties and remove it much later - but I really wonder if it's worth the effort for this).

@hughsie Feel free to comment on this, especially on the original intent of `update_text`, because from the API description that is indeed a bit dubious (and something we could maybe clarify?).

**Comment by Pointedstick** [comment]
I agree, Summary would be a better word than Reason. I'll see if I can get that changed. And it sounds like there is no way around doing some custom processing on our side. Thanks for taking a look anyway!

**Comment by ximion** [comment]
There is really no way to mangle changelogs in a way that works for all backends, they are just very different. Even between OpenSUSE and Fedora, a lot of differences exist, and especially between Debian-based OSes and e.g. Fedora.
Therefore, I wouldn't even attempt to do that - maybe make a Markdown parser that works for most of them, so changelogs are rendered a bit nicer, but not do more. Tbh, I would also completely ignore `update_text`, similar to what Apper does.
Instead, I would synthesize a summary from the bugfix information that is extracted from the changelogs by the respective backend (`bugzilla_urls`, `cve_urls`, `vendor_urls` arrays - yes, the names are also not ideal here ^^). With that, you can give information like "This update resolves 8 issues" that users can click on to jump to the changelog, or you can just display the URLs to the issue reports as summary directly.

**Comment by Pointedstick** [comment]
That's also a good idea!
