### ISSUE TITLE
aptcc: RequireRestart not working

### ISSUE THREAD

**Issue by apachelogger** [hughsie/PackageKit#234]
aptcc currently calls `pk_backend_job_require_restart` out of AptIntf dtor, unfortunately that seems to render the call nonfunctional.

Specifically, it seems `pk_backend_job_call_vfunc` kicks it out because the item is not enabled. I believe this is a side effect from calling it in the dtor (i.e. the transaction is probably finished at that point so giving any more updates wouldn't do anything). I can confirm that moving the call elsewhere in the transaction run results in the signal being correctly emitted.

I am not entirely confident that this is the right place in the code but the patch below fixes the emission. However IIRC we get the progress async through a pipe from apt, so by the time we run the stat the pkgid might be incorrect (as in: another package just configured and create the file, not the one we are currently handling). It may overall be better to continue suggesting all pkgids caused the signal, but move the emission from the dtor to the finished handling in `updateInterface`.

```
From 9ed16dbe9bb30d8ad64c6a0982460efb1382cb83 Mon Sep 17 00:00:00 2001
From: Harald Sitter <sitter@kde.org>
Date: Thu, 18 Jan 2018 17:51:00 +0100
Subject: [PATCH] always refresh reboot state on every progress update

---
 backends/aptcc/apt-intf.cpp | 15 +++++++++++++++
 1 file changed, 15 insertions(+)

diff --git a/backends/aptcc/apt-intf.cpp b/backends/aptcc/apt-intf.cpp
index 4291027..8476dea 100644
--- a/backends/aptcc/apt-intf.cpp
+++ b/backends/aptcc/apt-intf.cpp
@@ -440,6 +440,21 @@ void AptIntf::emitPackageProgress(const pkgCache::VerIterator &ver, PkStatusEnum
 {
     gchar *package_id;
     package_id = utilBuildPackageId(ver);
+    cerr << __FUNCTION__ << " " << package_id << endl;
+
+    if (g_file_test(REBOOT_REQUIRED, G_FILE_TEST_EXISTS)) {
+        cerr << "file exit" << endl;
+        struct stat restartStat;
+        g_stat(REBOOT_REQUIRED, &restartStat);
+
+        if (restartStat.st_mtime > m_restartStat.st_mtime) {
+            pk_backend_job_require_restart(m_job, PK_RESTART_ENUM_SYSTEM, package_id);
+        }
+
+        m_restartStat = restartStat;
+    }
+
+
     pk_backend_job_set_item_progress(m_job, package_id, status, percentage);
     g_free(package_id);
 }
-- 
2.7.4

```

**Comment by dantti** [comment]
There progress comes from a forked PackageKit that returns the status to the caller, which is in fact not a safe operation, but I can't judge which crash report was ever caused by this.
Anyway, until we unlock the apt database there won't be another concurrent process to touch the file so it should be safe to call that.
Your proposed patch has the issue that you will slow down all aptcc operations as it will keep checking if the file exist and stating on every pkg progress, well you know that.
The best place would then to emit prior emitting FINISHED, I'll try to take a look at where this would be best placed.
