### ISSUE TITLE
wrong URL parsing when downloading GPG key

### ISSUE THREAD

**Issue by fedelibre** [hughsie/PackageKit#304]
As [I reported here](https://bugzilla.redhat.com/show_bug.cgi?id=1585276#c6) while debugging a high CPU issue with packagekitd, it seems that packagekit is parsing incorrectly the GPG key URL defined in a repository. It's a COPR repository and it happened to be a disabled repository (I wonder if it's worth checking the GPG key of a disabled repository...).

journalctl showed this:

```
dic 23 16:04:07 fedora packagekitd[1292]: Skipping refresh of cygn-pulseaudio-dlna: Failed to download gpg key for repo 'cygn-pulseaudio-dlna': Curl error (28): Timeout was reached for https://copr-be.cloud.fed>
```
As you can see in [the repo file], the gpg key line is:

    gpgkey=https://copr-be.cloud.fedoraproject.org/results/cygn/pulseaudio-dlna/pubkey.gpg

curl timed out while trying to reach https://copr-be.cloud.fed, so it seems that **packagekit assumes the URL can have only one subdomain**.

**Comment by kalev** [comment]
If I understand this right the issue here is that you think that packagekit is parsing https://copr-be.cloud.fedoraproject.org/results/cygn/pulseaudio-dlna/pubkey.gpg incorrectly as https://copr-be.cloud.fed ?

I don't think this is the case here. The error message is just truncated by something, I'd assume the pager in the terminal (less) and just shows > where it goes off screen. If you press the right arrow when viewing journalctl output in less you should get the full error message.

**Comment by fedelibre** [comment]
Ooops, you're right, dumb me!
Here's the full log:

```
dic 23 09:27:07 fedora packagekitd[1295]: Skipping refresh of cygn-pulseaudio-dlna: Failed to download gpg key for repo 'cygn-pulseaudio-dlna': Curl error (28): Timeout was reached for https://copr-be.cloud.fedoraproject.org/results/cygn/pulseaudio-dlna/pubkey.gpg [Connection timed out after 30001 milliseconds]
```
