### ISSUE TITLE
[Feature Request] Support AUR

### ISSUE THREAD

**Issue by polarathene** [hughsie/PackageKit#340]
It'd be nice to see support for the [Arch User Repository (AUR)](https://aur.archlinux.org/) in PackageKit. GUI package managers that use this project aren't able to support AUR on Arch Linux otherwise afaik?

Such as Discover:

https://www.reddit.com/r/kde/comments/da4yfg/aur_in_discover/

https://www.reddit.com/r/archlinux/comments/d4iu5q/aur_support_on_kde_discover/

**Comment by aleixpol** [comment]
PackageKit works fine on ArchLinux, AUR isn't necessary.
Some things are only available there but AUR isn't supported by the ArchLinux project (and for good reasons).

I'd suggest getting projects that aren't part of the distros from flatpak or snap otherwise.

PS: I'm Discover's maintainer

**Comment by polarathene** [comment]
I didn't claim PackageKit doesn't work with ArchLinux... It's not uncommon to want to use the AUR though.

> AUR isn't supported by the ArchLinux project (and for good reasons).

Right... but there is an abundance of AUR helpers, and AUR support in alternative package manager GUIs such as Octopi or Pamac. You may not choose to use the AUR(if you're an Arch user?), but surely you're aware that it's popular with Arch users?

The user should be aware of the risk of using the AUR, it is their decision to do so via manual use, an AUR CLI helper, or explicitly enabling AUR support in the supported GUI package managers.

You can be a user that already uses the AUR with certain packages you trust, you could have reviewed the PKGBUILD and what is being installed/run, perhaps a GPG key is added for additional trust, you can lock the package version and update it when you're ready to(potentially reviewing any changes), or none of that, it's the users risk.

> I'd suggest getting projects that aren't part of the distros from flatpak or snap otherwise.

Not everyone wants to repackage and maintain the software they use. That's kind of the whole benefit of using a package manager for centralizing that, and with the AUR, the community can share such a packaging effort with others easily(just like other distros have similar community repositories that could be leveraged for the same purpose). Yes Flatpak and Snap can suitably work as a packaging alternative, but it's not always viable.

I have no interest in running Snap, and Flatpak support for electron apps is not as easily available. Do Flatpak/Snap even support equivalent of git(master branch) packages? What about proprietary packages that you do not have source for? Chrome or Firefox? Those only seem available in Snap, is there something preventing them from being packaged in Flatpak?(If it were doable/easy, one would think Flathub would have those available by now?)

My VPN providers app(available on the AUR), this isn't something I would expect to work well with Flatpak or Snap, or at the very least require a fair bit more experience/knowledge to package for, rather than be happy user via the package support on their distro(which understandably cannot exist in the official repos afaik).

Some of the AUR packages are maintained by the developers themselves, Linux may not be a platform where they can support Flatpak/Snap though ironically. There appears to be issues when the package would need access to the GPU, be that drivers or features like CUDA/ROCm based on some search results. 

And packages that I use for local development myself that provide a library and bind to CUDA and cuDNN(system package, not in AUR), these can be a pain to setup/install locally as I don't deal with C++(one package I tried to compile and setup myself was particularly troublesome, the developers linux support was poorly documented, others also tried in hopes of attempting a Flatpak build once someone was able to compile the code successfully, but no luck in 2 years). For development packages where they provide a library to be linked with your own code, I'm not sure how Snap or Flatpak fit into that, for example ArrayFire.

PackageKit seems great, but in this case if there's a hard decision against ever supporting the AUR, it's unlikely something that I or others can adopt any time soon or at all. There's just too much hassle/friction giving up on something highly valuable(that has caused no harm with my usage of it or for many others that use the AUR with common sense). 

Personally, closing the issue for such support, for the reasons given, seems to be against the point of what PackageKit is developed to solve:

> *PackageKit is a system designed to make installing and updating software on your computer easier. The primary design goal is to unify all the software graphical tools used in different distributions, and use some of the latest technology like PolicyKit.*

If I could replace AUR with Flatpak or Snap, great. Then PackageKit is neat for using across distros, especially with the excellent Discover app. But afaik, I can't replace everything I use from the AUR(which is a huge attraction to using Arch in the first place, I've not found other distros with the equivalent package offering/quality/experience).. I'm unable to adopt PackageKit, or Discover for that matter(which I'd like to), as it does not make it easier, it makes the process harder(two separate apps/updaters, with Discover technically being redundant), or of a degraded quality/experience(Flatpak/Snap packages aren't always on par with what AUR equivalents will provide).

> PS: I'm Discover's maintainer

Great! Why are you so against support for such a feature? If you don't personally have any interest or use of the AUR, why are you against other users that actively use and enjoy it, especially when other alternatives to Discover on Arch have offered such for many years successfully?

I'm not requesting that you implement this yourself. But in closing the issue and with your reasoning/stance, you discourage such a feature being welcomed to PackageKit(and thus Discover).

> *PackageKit isn't meant to replace these tools, instead providing a common set of abstractions that can be used by standard GUI and text mode package managers.*

> *What PackageKit is not:*
  - *Produced by any one vendor.*

Are you closing this issue as a Discover maintainer, or on behalf of PackageKit maintainers?

While it's not immediately clear, and as I don't use other distros, would I be wrong to say that on Fedora with RPMFusion or OpenSUSE with third-party community package repos like Packman, PackageKit supports these(and perhaps as a result Discover?), these are some how safer than using AUR with Arch?

> *RPM Fusion provides software that the Fedora Project or Red Hat doesn't want to ship. That software is provided as precompiled RPMs for all current Fedora versions and current Red Hat Enterprise Linux or clones versions; you can use the RPM Fusion repositories with tools like yum and PackageKit.*

> *RPM Fusion is a merger of Dribble, Freshrpms, and Livna; our goal is to simplify end-user experience by grouping as much add-on software as possible in a single location.* - [Source](https://rpmfusion.org/)

[Sounds pretty similar to the AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) no?:

> *The Arch User Repository (AUR) is a community-driven repository for Arch users. It contains package descriptions (PKGBUILDs) that allow you to compile a package from source with makepkg and then install it via pacman*

Or rather, the AUR being community driven rather than managed via trusted users only, is more like PPA, OBS and COPR? [Which PackageKit appears to be more than happy to support](https://github.com/hughsie/PackageKit/issues/302), you even chimed in on that linked issue yourself.

---

So can you please clarify why support for the AUR is a big no-no for PackageKit? Would it not be possible to use a backend and some approach for requesting the user enable the support(disabled by default)?

If that were then supported, and you feel Discover can support third-party/unofficial package repos on other distros via PackageKit, but not AUR, that's the developers of Discover's choice to restrict users (despite being about empowering users via their GUI).

**Comment by beliys** [comment]
@aleixpol I agree with @polarathene since unfortunately, at the moment, AUR has no analogues and it is physically impossible to replace it with flatpak or snap. Arch/Manjaro users completely understand the risk associated with using packages from AUR, but in my opinion it would be best to use the pamac experience when AUR is disabled by default and needs to be activated and upon activation the user receives a warning about the risks of using AUR. At the same time, without AUR support, Arch/Manjaro users will not be able to fully use Discover and will be forced to use another application or use several.
I really hope for your understanding.

**Comment by CLOVIS-AI** [comment]
There doesn't seem to be much activity in this issue, it would be nice to have a reply from the maintainers.

**Comment by hughsie** [comment]
> The decision to close this issue seems flawed

I think the issue was correctly closed, sorry. I think Flathub is what you need to look at nowadays.

**Comment by beliys** [comment]
@hughsie In my opinion, it would be optimal to provide the opportunity for users to make their own choice. Technically, how difficult is it to implement?

**Comment by Adlyq** [comment]
yay provides the same cli as pacman, just `ln -s <yay> <pacman>`, and you're basically there. But this simplicity inevitably leads to other problems. Is it possible to use a namespace-like technique? I'm new to linux.

**Comment by hron84** [comment]
> Technically, how difficult is it to implement?

> yay provides the same cli as pacman, just `ln -s <yay> <pacman>` ...

Most integrations that involve Pacman does not use the Pacman CLI interface at all. Instead, they integrate with `libalpm`, which is a C library that Pacman is based on. However libalpm does not have an AUR support, so Pacman does not have this. For softwares or frameworks wanting integrate with AUR, they should technically develop their own solution for supporting it.

"Why?" you could ask. It is because existing CLI tools have performance issues (a GUI could do a 10-20 query against the software db per second and spawn/bootstrap time of the CLI tools is just too slow for this, even if they are _seem_ to be fast _for humans_) , not reliable and do not provide a standardised output format (like JSON or XML) that can be easily consumed by these frameworks and tools. While a CLI tool is OK for managing AUR packages from CLI, it is not suitable for back a GUI. For example, Pacman (and YAY also) has multilanguage support, but if you run your OS in different language than English, GUIs that are backed by CLI tools could have challenges parsing the output of YAY. It will be Unicode, it will contain weird characters, delimiters can be funny and all sort of problems. While it sounds relatively easy to solve, it is still the tip of a huge iceberg. There is a lot of problems with CLI tools other than multilanguage support, which I do not want to expand here: exit code handling, timeout handling, etc. Also, CLI tools are easy target to be replaced ("... just `ln -s` ...") so as a developer, you cannot trust that if you call the `pacman` command, the real Pacman will fire up or something else.

That's why most frameworks and softwares do not support AUR at all. And in the foreseeable future without active help of the Arch community, it will never change. We need libraries that can both handle AUR packages and delegate calls to libalpm, we need standardised, language-agnostic output formats that can be parsed and we need to support projects like PackageKit to be able to integrate with the new standards.
