### ISSUE TITLE
Packagkit Python Backend Fix Suggestion

### ISSUE THREAD

**Issue by blackPantherOS** [hughsie/PackageKit#73]
Hi, We are using packagekit python backed in blackPanther, but we meet with a little problem. Example Apper does not provide args[3] and threfoe packagekit backend is crashed . This is a suggestion to fix this problem:

|--- backend.py.orig     2015-06-12 22:44:16.000000000 +0200
|+++ backend.py  2015-07-31 12:35:41.000000000 +0200
|@@ -626,7 +626,11 @@
|             transaction_flags = args[0].split(';')
|             package_ids = args[1].split(PACKAGE_IDS_DELIM)
|             allowdeps = _text_to_bool(args[2])
|-            autoremove = _text_to_bool(args[3])
|+            autoremove = False
|+            try: 
|+               autoremove = _text_to_bool(args[3])
|+           except:
|+               pass
|             self.remove_packages(transaction_flags, package_ids, allowdeps, autoremove)
|             self.finished()
|         elif cmd == 'repo-enable':

Sorry if my English too poor

**Comment by hughsie** [comment]
Which python backend are you using? apt? yum?

**Comment by blackPantherOS** [comment]
We forked Smart PM and working on smartBackend too... I saw that PKit drop this backend already but I see few opportunity in smart-pm engine...

**Comment by hughsie** [comment]
So what version of PackageKit are you using? I think you probably want to fix your pk-backend-smart.c if I understand correctly.

**Comment by blackPantherOS** [comment]
We using the PackageKit 1.0.6 
I don't remember sure, I think the pk-backend-smart.c was good,  the helper, smartBackend.py and the smart-1.4 was very outdated. Now got there, that the install/remove/update working again in promt and Apper too.

**Comment by blackPantherOS** [comment]
The one original problem under blackPanther example like this:
http://openmamba.org/it/forums/topic/errore-disinst-inst-synfigstudio/

errore:
Error Type:
Error Value: list index out of range
File : /usr/share/PackageKit/helpers/smart/smartBackend.py, line 1452, in
main()
File : /usr/share/PackageKit/helpers/smart/smartBackend.py, line 1443, in main
backend.dispatcher(sys.argv[1:])
File : /usr/lib/python2.7/site-packages/packagekit/backend.py, line 721, in dispatcher
self.dispatch_command(args[0], args[1:])
File : /usr/lib/python2.7/site-packages/packagekit/backend.py, line 636, in dispatch_command
autoremove = _text_to_bool(args[3])

**Comment by afb** [comment]
The smart backend was dropped by @hughsie from PackageKit 1.0, at the same time when Smart was moved from Launchpad to GitHub ([smartpm/smart](https://github.com/smartpm/smart)). I don't know anyone else using the Mandriva packages backend (rpm) with smart, since the Unity Linux distribution stopped. Or PK with Smart, either.

**Comment by blackPantherOS** [comment]
afb@
I know, thanks , We would like using smart in future and as main package engine in next blackPanther release. And now just the system use the urpmi backend. But we want drop urpmi connections because urpmi the source of too many problems.

**Comment by hughsie** [comment]
So you're using 1.0.6 with a mega-patch to add back the smart backend? If so, you need to fix the pk-backend-smart.c file you've added.

**Comment by blackPantherOS** [comment]
Yes, we add back smart support in packagekig 1.0.6 and working too again. I will double check the pk-backend-smart.c

**Comment by afb** [comment]
Okay, found your forked copy of old smart 1.4.1 at [blackPantherOS/packagemanagement] (https://github.com/blackPantherOS/packagemanagement/tree/master/smartpm). I'm not sure what the process is for bringing back old abandoned backends in PackageKit, but I'm assuming that it would start off as a branch and then update the API from the old 0.9 version or something like that...

I am not planning to do anything with it myself, but can answer questions about the old PK backend (as long as I remember them). As far as I can remember, it was a pretty straight-forward python backend. I suppose most people would like to use libsolv (hawkey) instead of python, but that's another story.

**Comment by blackPantherOS** [comment]
I understand thank you to your response. We are already using still now the smartpm to few process, We will push to github my modifications, and if someone want to using, there will available all codes. Regards.

**Comment by afb** [comment]
I also think that you should bring it up with the mailing list, nothing much has changed since the [decision](http://lists.freedesktop.org/archives/packagekit/2014-September/026292.html) was taken to drop the smart PK backend. On the contrary, both dnf and hawkey are more finished now...
